/* Avatar picker — character → look → username → city → share.
 *
 * Data comes from characters.js (regenerated by tools/slice_sheet.py) and
 * events.js (hand-edited). Nothing here is hard-coded to a particular
 * character, variant count, or tour stop.
 *
 * Embedding: set AvatarPicker.onComplete before or after this file runs. It
 * fires once the share step is reached, with the full selection.
 */
(function () {
  "use strict";

  var CHARACTERS = (window.CHARACTERS || []).filter(function (c) { return c.variants.length; });
  var EVENTS = window.EVENTS || [];
  var STORE_KEY = "avatar-picker:selection";

  var NAME_MIN = 3, NAME_MAX = 20;
  var NAME_OK = /^[A-Za-z0-9][A-Za-z0-9 _-]*[A-Za-z0-9]$/;

  var EVENT_NAME = "GRC Barcade";
  var HASHTAGS = "#GRCBarcade #GRC #Compliance";

  var state = { step: 1, character: null, variant: null, username: "", event: null };
  var cardBlob = null;

  var $ = function (id) { return document.getElementById(id); };

  /* ------------------------------------------------------------- helpers -- */

  function defaultVariant(character) {
    var i = (character.default || 1) - 1;
    return character.variants[i] ? i : 0;
  }

  function card(imgSrc, caption, alt, selected, onPick) {
    // `caption` may be null — most sheets show art only. `alt` is separate so
    // screen readers still get something when nothing is printed on the tile.
    var b = document.createElement("button");
    b.type = "button";
    b.className = "card";
    b.setAttribute("aria-pressed", selected ? "true" : "false");

    var img = document.createElement("img");
    img.className = "art";
    img.src = imgSrc;
    img.alt = alt || caption || "";
    img.loading = "lazy";
    b.appendChild(img);

    if (caption) {
      var cap = document.createElement("span");
      cap.className = "cap";
      cap.textContent = caption;
      b.appendChild(cap);
    }

    b.addEventListener("click", onPick);
    return b;
  }

  function loadImage(src) {
    return new Promise(function (resolve, reject) {
      var img = new Image();
      img.onload = function () { resolve(img); };
      img.onerror = reject;
      img.src = src;
    });
  }

  function cityLine(e) {
    return e.area ? e.city + " (" + e.area + ")" : e.city;
  }

  /** How a character reads after a username. Archetypes take "the"; proper
   *  names like "Agent Ic" take "playing as". */
  function byline(c) {
    return c.proper ? "playing as " + c.name : c.name.replace(/^The\b/, "the");
  }

  /* --------------------------------------------------------------- steps -- */

  function renderCharacters() {
    var grid = $("character-grid");
    grid.textContent = "";

    if (!CHARACTERS.length) {
      var e = document.createElement("div");
      e.className = "empty";
      e.innerHTML = "No characters yet. Drop a contact sheet in <code>tools/sheets/src/</code>, " +
                    "add its <code>.json</code>, and run <code>python3 tools/slice_sheet.py</code>.";
      grid.appendChild(e);
      return;
    }

    CHARACTERS.forEach(function (c) {
      var v = c.variants[defaultVariant(c)];
      grid.appendChild(card(v.file, c.name, c.name, state.character === c, function () {
        // Switching characters invalidates the variant choice.
        if (state.character !== c) {
          state.character = c;
          state.variant = defaultVariant(c);
        }
        go(2);
      }));
    });
  }

  function renderVariants() {
    var c = state.character;
    if (!c) return;

    $("variant-sub").textContent = c.tagline
      ? c.variants.length + " looks for " + c.name + " — " + c.tagline
      : c.variants.length + " looks for " + c.name + ".";

    var grid = $("variant-grid");
    grid.textContent = "";
    c.variants.forEach(function (v, i) {
      grid.appendChild(card(v.file, c.captions ? v.name : null,
                            c.name + ", look " + (i + 1), state.variant === i, function () {
        state.variant = i;
        renderVariants();
        go(3);
      }));
    });
  }

  function renderPreview() {
    var c = state.character;
    if (!c) return;
    var v = c.variants[state.variant];
    var art = $("preview-art");
    // The preview is the one place big enough to need the @2x file.
    art.src = v.file2x || v.file;
    art.alt = c.name + ", look " + (state.variant + 1);

    // Cap it at life size. That's the 1x frame from the manifest — the loaded
    // image is twice that, and blowing art up past its real detail is exactly
    // what makes these sheets look soft.
    art.parentNode.style.setProperty("--art-w", ((c.frame && c.frame[0]) || 240) + "px");

    $("preview-name").textContent = state.username;
    $("preview-meta").textContent = c.captions ? byline(c) + " · " + v.name : byline(c);
  }

  function renderCities() {
    var grid = $("city-grid");
    grid.textContent = "";
    EVENTS.forEach(function (e) {
      var b = document.createElement("button");
      b.type = "button";
      b.className = "city";
      b.setAttribute("aria-pressed", state.event === e ? "true" : "false");
      b.innerHTML = '<div class="when"></div><div class="where"></div>' +
                    (e.area ? '<div class="area"></div>' : "") +
                    '<div class="venue"></div>';
      b.querySelector(".when").textContent = e.dateLabel;
      b.querySelector(".where").textContent = e.city;
      if (e.area) b.querySelector(".area").textContent = e.area + " area";
      b.querySelector(".venue").textContent = e.venue;
      b.addEventListener("click", function () {
        state.event = e;
        go(5);
      });
      grid.appendChild(b);
    });
  }

  /* ---------------------------------------------------------- validation -- */

  function nameError(raw) {
    var n = raw.trim();
    if (!n) return "";                                       // untouched, not an error yet
    if (n.length < NAME_MIN) return "At least " + NAME_MIN + " characters.";
    if (n.length > NAME_MAX) return "At most " + NAME_MAX + " characters.";
    if (!NAME_OK.test(n)) return "Letters, numbers, spaces, - and _ only.";
    return "";
  }

  function syncName() {
    var input = $("username");
    var raw = input.value;
    var err = nameError(raw);
    var valid = raw.trim().length >= NAME_MIN && !err;

    state.username = raw.trim();
    $("username-count").textContent = raw.length + " / " + NAME_MAX;
    $("username-error").textContent = err;
    input.setAttribute("aria-invalid", err ? "true" : "false");
    $("confirm").disabled = !valid;
    $("preview-name").textContent = state.username;
  }

  /* ---------------------------------------------------------- share card -- */

  var PALETTE = { cyan: "#00dce9", magenta: "#ff3399", orange: "#ffa84f",
                  bg: "#0a1526", deep: "#060e1b", ink: "#eaf2ff", dim: "#93a8c8" };

  function roundRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }

  /** Shrink until it fits — usernames and venue names vary a lot in length. */
  function fitText(ctx, text, max, weight, size, family) {
    do {
      ctx.font = weight + " " + size + "px " + family;
      if (ctx.measureText(text).width <= max) break;
      size -= 2;
    } while (size > 12);
    return size;
  }

  function glow(ctx, x, y, r, color, alpha) {
    var g = ctx.createRadialGradient(x, y, 0, x, y, r);
    g.addColorStop(0, color);
    g.addColorStop(1, "rgba(10,21,38,0)");
    ctx.globalAlpha = alpha;
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, 1080, 1080);
    ctx.globalAlpha = 1;
  }

  function drawCard() {
    var canvas = $("share-canvas");
    var ctx = canvas.getContext("2d");
    var c = state.character, v = c.variants[state.variant], e = state.event;
    var S = 1080, body = '"Mulish", system-ui, sans-serif', title = '"Merriweather", Georgia, serif';

    ctx.clearRect(0, 0, S, S);
    ctx.fillStyle = PALETTE.bg;
    ctx.fillRect(0, 0, S, S);
    glow(ctx, 150, 90, 700, PALETTE.cyan, .20);
    glow(ctx, 950, 180, 640, PALETTE.magenta, .18);
    glow(ctx, 560, 1060, 620, PALETTE.orange, .15);

    // gradient hairline frame
    var stroke = ctx.createLinearGradient(40, 40, S - 40, S - 40);
    stroke.addColorStop(0, PALETTE.cyan);
    stroke.addColorStop(.55, PALETTE.magenta);
    stroke.addColorStop(1, PALETTE.orange);
    ctx.strokeStyle = stroke;
    ctx.lineWidth = 4;
    roundRect(ctx, 34, 34, S - 68, S - 68, 44);
    ctx.stroke();

    return loadImage(v.file2x || v.file).then(function (art) {
      // No logo up top: the card says GRC BARCADE in the headline already, and
      // repeating it just steals room from the avatar.
      // Avatar aspect-fits a fixed box, so every character lands the same.
      var boxT = 128, boxH = 432, boxW = 640;
      var k = Math.min(boxW / art.width, boxH / art.height);
      var aw = art.width * k, ah = art.height * k;
      ctx.drawImage(art, (S - aw) / 2, boxT + (boxH - ah) / 2, aw, ah);

      ctx.textAlign = "center";

      var size = fitText(ctx, state.username, 760, 900, 60, title);
      ctx.fillStyle = PALETTE.ink;
      ctx.font = "900 " + size + "px " + title;
      ctx.fillText(state.username, S / 2, 640);

      // character badge — reads as a class, so it never competes with the name
      var tag = byline(c);
      ctx.font = "700 " + fitText(ctx, tag, 620, 700, 28, body) + "px " + body;
      var tw = ctx.measureText(tag).width;
      ctx.strokeStyle = "rgba(0,220,233,.55)";
      ctx.fillStyle = "rgba(0,220,233,.10)";
      ctx.lineWidth = 2;
      roundRect(ctx, (S - tw) / 2 - 26, 662, tw + 52, 50, 25);
      ctx.fill();
      ctx.stroke();
      ctx.fillStyle = PALETTE.cyan;
      ctx.fillText(tag, S / 2, 695);

      if (ctx.letterSpacing !== undefined) ctx.letterSpacing = "6px";
      ctx.fillStyle = PALETTE.cyan;
      ctx.font = "800 25px " + body;
      ctx.fillText("I'M GOING TO THE", S / 2, 764);
      if (ctx.letterSpacing !== undefined) ctx.letterSpacing = "0px";

      var head = ctx.createLinearGradient(180, 0, 900, 0);
      head.addColorStop(0, PALETTE.cyan);
      head.addColorStop(.55, PALETTE.magenta);
      head.addColorStop(1, PALETTE.orange);
      ctx.fillStyle = head;
      ctx.font = "900 " + fitText(ctx, EVENT_NAME.toUpperCase(), 860, 900, 82, title) + "px " + title;
      ctx.fillText(EVENT_NAME.toUpperCase(), S / 2, 850);

      ctx.strokeStyle = "rgba(147,168,200,.35)";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(330, 895);
      ctx.lineTo(750, 895);
      ctx.stroke();

      ctx.fillStyle = PALETTE.ink;
      ctx.font = "800 " + fitText(ctx, cityLine(e) + "  ·  " + e.dateLabel, 800, 800, 40, body) + "px " + body;
      ctx.fillText(cityLine(e) + "  ·  " + e.dateLabel, S / 2, 952);

      ctx.fillStyle = PALETTE.dim;
      ctx.font = "600 " + fitText(ctx, e.venue, 800, 600, 29, body) + "px " + body;
      ctx.fillText(e.venue, S / 2, 996);

      cardBlob = null;                                       // invalidate the cached export
    });
  }

  function cardFile() {
    if (cardBlob) return Promise.resolve(cardBlob);
    return new Promise(function (resolve) {
      $("share-canvas").toBlob(function (blob) {
        cardBlob = blob;
        resolve(blob);
      }, "image/png");
    });
  }

  /* ------------------------------------------------------------- sharing -- */

  function status(msg) {
    $("share-status").textContent = msg;
    if (msg) setTimeout(function () {
      if ($("share-status").textContent === msg) $("share-status").textContent = "";
    }, 4000);
  }

  function captionText() {
    var e = state.event, c = state.character;
    return "I'm going to the " + EVENT_NAME + " in " + cityLine(e) + " — " +
           e.dateLabel + " at " + e.venue + ".\n\n" +
           "Rolling in as " + byline(c).replace(/^playing as /, "") + ". " +
           HASHTAGS + (e.url ? "\n" + e.url : "");
  }

  function copyCaption() {
    var text = $("caption").value;
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text);
    }
    // http-only or older browsers: fall back to a throwaway selection
    return new Promise(function (resolve, reject) {
      var ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      var ok = document.execCommand && document.execCommand("copy");
      document.body.removeChild(ta);
      ok ? resolve() : reject(new Error("copy blocked"));
    });
  }

  function downloadCard() {
    return cardFile().then(function (blob) {
      var url = URL.createObjectURL(blob);
      var a = document.createElement("a");
      a.href = url;
      a.download = "grc-barcade-" + state.event.id + "-" + state.username.replace(/\W+/g, "-") + ".png";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(function () { URL.revokeObjectURL(url); }, 5000);
    });
  }

  function nativeShare() {
    return cardFile().then(function (blob) {
      var file = new File([blob], "grc-barcade.png", { type: "image/png" });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        return navigator.share({ files: [file], text: $("caption").value });
      }
      return navigator.share({ text: $("caption").value });
    });
  }

  function shareLinkedIn() {
    // LinkedIn dropped prefilled text from share-offsite, so: copy the caption,
    // hand them the composer, and let them paste + attach the image.
    var e = state.event;
    var url = e.url
      ? "https://www.linkedin.com/sharing/share-offsite/?url=" + encodeURIComponent(e.url)
      : "https://www.linkedin.com/feed/?shareActive=true&text=" + encodeURIComponent($("caption").value);

    Promise.all([copyCaption().catch(function () {}), downloadCard()]).then(function () {
      status("Caption copied, image downloaded — paste and attach in LinkedIn.");
      window.open(url, "_blank", "noopener");
    });
  }

  function shareInstagram() {
    // Instagram has no web composer at all, so the honest path is: give them
    // the file and the words, and let them post from the app.
    if (navigator.canShare) {
      return nativeShare().then(function () { status("Shared."); }, function () { instagramFallback(); });
    }
    instagramFallback();
  }

  function instagramFallback() {
    Promise.all([copyCaption().catch(function () {}), downloadCard()]).then(function () {
      status("Image downloaded and caption copied — post it from the Instagram app.");
    });
  }

  /* ------------------------------------------------------------ routing -- */

  function reachable(n) {
    if (n <= 1) return true;
    if (n === 2) return !!state.character;
    if (n === 3) return state.variant !== null && !!state.character;
    if (n === 4) return state.variant !== null && !nameError(state.username) &&
                        state.username.length >= NAME_MIN;
    return reachable(4) && !!state.event;
  }

  function go(step) {
    while (step > 1 && !reachable(step)) step--;             // never skip ahead of the data

    state.step = step;
    [1, 2, 3, 4, 5].forEach(function (n) { $("step-" + n).hidden = n !== step; });

    Array.prototype.forEach.call(document.querySelectorAll(".rail-step"), function (el) {
      var n = Number(el.dataset.goto);
      el.dataset.done = n < step ? "1" : "0";
      el.dataset.clickable = reachable(n) ? "1" : "0";
      if (n === step) el.setAttribute("aria-current", "step");
      else el.removeAttribute("aria-current");
    });

    if (step === 1) renderCharacters();
    if (step === 2) renderVariants();
    if (step === 3) { renderPreview(); syncName(); $("username").focus(); }
    if (step === 4) renderCities();
    if (step === 5) finish();

    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  /* ------------------------------------------------------------- finish -- */

  function selection() {
    var c = state.character, v = c.variants[state.variant], e = state.event;
    return {
      characterId: c.id,
      characterName: c.name,
      variantIndex: state.variant + 1,
      variantName: v.name,
      image: v.file,
      image2x: v.file2x,
      username: state.username,
      eventId: e && e.id,
      eventCity: e && cityLine(e),
      eventDate: e && e.date,
      eventVenue: e && e.venue
    };
  }

  function finish() {
    var sel = selection();
    var e = state.event;

    $("share-sub").textContent =
      "You're on the list for " + cityLine(e) + " — " + e.dateLabel + " at " + e.venue + ".";
    $("caption").value = captionText();
    $("share-note").textContent = navigator.canShare
      ? "Instagram has no web posting, so “Post on Instagram” hands the image and caption to your phone's share sheet. LinkedIn opens its composer — the caption is already on your clipboard, just attach the image."
      : "Instagram can only post from the app, so we download the image and copy the caption for you. LinkedIn opens its composer with the caption on your clipboard — attach the downloaded image there.";

    $("share-native").hidden = !navigator.canShare;

    try { localStorage.setItem(STORE_KEY, JSON.stringify(sel)); } catch (err) { /* private mode */ }
    drawCard();

    if (typeof window.AvatarPicker.onComplete === "function") window.AvatarPicker.onComplete(sel);
  }

  function restore() {
    var saved;
    try { saved = JSON.parse(localStorage.getItem(STORE_KEY) || "null"); } catch (e) { return; }
    if (!saved) return;
    var c = CHARACTERS.filter(function (x) { return x.id === saved.characterId; })[0];
    if (!c) return;
    state.character = c;
    state.variant = c.variants[saved.variantIndex - 1] ? saved.variantIndex - 1 : defaultVariant(c);
    state.username = saved.username || "";
    state.event = EVENTS.filter(function (e) { return e.id === saved.eventId; })[0] || null;
    $("username").value = state.username;
  }

  /* ------------------------------------------------------------- wiring -- */

  document.addEventListener("DOMContentLoaded", function () {
    restore();

    $("back-1").addEventListener("click", function () { go(1); });
    $("back-2").addEventListener("click", function () { go(2); });
    $("back-3").addEventListener("click", function () { go(3); });
    $("back-4").addEventListener("click", function () { go(4); });
    $("confirm").addEventListener("click", function () { go(4); });

    $("username").addEventListener("input", syncName);
    $("username").addEventListener("keydown", function (e) {
      if (e.key === "Enter" && !$("confirm").disabled) go(4);
    });

    $("surprise").addEventListener("click", function () {
      var n = state.character.variants.length;
      var pick = state.variant;
      while (n > 1 && pick === state.variant) pick = Math.floor(Math.random() * n);
      state.variant = pick;
      renderVariants();
      document.querySelectorAll("#variant-grid .card")[pick]
        .scrollIntoView({ block: "center", behavior: "smooth" });
    });

    $("share-download").addEventListener("click", function () {
      downloadCard().then(function () { status("Image downloaded."); });
    });
    $("share-copy").addEventListener("click", function () {
      copyCaption().then(function () { status("Caption copied."); },
                         function () { status("Couldn't copy — select the text and copy it."); });
    });
    $("share-native").addEventListener("click", function () {
      nativeShare().catch(function () { /* user dismissed the sheet */ });
    });
    $("share-linkedin").addEventListener("click", shareLinkedIn);
    $("share-instagram").addEventListener("click", shareInstagram);

    $("restart").addEventListener("click", function () {
      state.character = null; state.variant = null; state.event = null; state.username = "";
      $("username").value = "";
      try { localStorage.removeItem(STORE_KEY); } catch (e) { /* private mode */ }
      go(1);
    });

    Array.prototype.forEach.call(document.querySelectorAll(".rail-step"), function (el) {
      el.addEventListener("click", function () {
        if (el.dataset.clickable === "1") go(Number(el.dataset.goto));
      });
    });

    var toggle = $("theme-toggle");
    toggle.addEventListener("click", function () {
      var light = document.documentElement.dataset.theme === "light";
      document.documentElement.dataset.theme = light ? "dark" : "light";
      toggle.textContent = light ? "Light mode" : "Dark mode";
    });

    // Merriweather/Mulish arrive after first paint; redraw so the card isn't
    // rendered in the fallback serif.
    if (document.fonts && document.fonts.ready) {
      document.fonts.ready.then(function () { if (state.step === 5) drawCard(); });
    }

    go(1);
  });

  window.AvatarPicker = {
    onComplete: window.AvatarPicker && window.AvatarPicker.onComplete || null,
    getSelection: function () {
      return state.character && state.variant !== null ? selection() : null;
    }
  };
})();
